-- Additive extension for the live local ERCOPAC demo database.
BEGIN;

INSERT INTO organisations (name, code, country, domain, status, plan, user_limit, org_admin_licence_limit, general_manager_licence_limit, department_manager_licence_limit, employee_licence_limit, monthly_revenue, health_score, created_at, max_failed_logins, password_min_length, flag_at_risk, flag_payment_overdue, flag_upsell_opportunity, flag_vip_priority, flag_pilot_features, flag_under_review, active)
VALUES ('Aurora Process Solutions SAS', 'AURORA', 'France', 'aurora-process.example', 'SUSPENDED', 'PROFESSIONAL', 20, 1, 1, 3, 15, 0.00, 41, CURRENT_TIMESTAMP - INTERVAL '80 days', 5, 12, true, true, false, false, false, true, false);

INSERT INTO users (full_name, email, password_hash, role, organisation_id, employee_code, department_code, job_title, seniority, hours_per_day, days_per_week, workdays, internal_user, default_rate, rate_type, currency, active)
VALUES ('Claire Dubois', 'claire.dubois@aurora-process.example', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ORG_ADMIN', (SELECT id FROM organisations WHERE code = 'AURORA'), 'AU-ADM-001', 'ADMIN', 'Organisation Administrator', 'SENIOR', 8, 5, 'MON-FRI', true, 90.00, 'HOURLY', 'EUR', false);

INSERT INTO projects (code, name, organisation_id, short_name, portfolio, org_assignment, country, project_type, project_phase, priority, planned_start, planned_end, project_budget, total_project_budget, project_manager_id, customer, category, risk_level, estimated_cost, project_manager_name, program_manager_name, sales_manager_name, archived, progress, application_type, comment) VALUES
('NSC-26-021', 'Bosch Vision Inspection Upgrade', (SELECT id FROM organisations WHERE code = 'NSIA'), 'Bosch Vision', 'Factory Automation', 'DACH Operations', 'Germany', 'Engineering Change', 'EXECUTION', 'HIGH', CURRENT_DATE - 45, CURRENT_DATE + 55, 760000.00, 815000.00, (SELECT id FROM users WHERE email = 'daniel.keller@northstar-ia.example'), 'Bosch Rexroth AG', 'Industrial Automation', 'HIGH', 790000.00, 'Daniel Keller', 'Daniel Keller', 'Marie Hoffmann', false, 34, 'PROJECTUM', 'Delayed vision-inspection upgrade; supplier integration recovery is in progress.'),
('NSC-25-008', 'Hygienic Filling Compliance Renewal', (SELECT id FROM organisations WHERE code = 'NSIA'), 'Filling Compliance', 'Life Sciences', 'DACH Operations', 'Germany', 'Turnkey Delivery', 'COMPLETED', 'MEDIUM', CURRENT_DATE - 420, CURRENT_DATE - 70, 530000.00, 560000.00, (SELECT id FROM users WHERE email = 'sofia.roth@northstar-ia.example'), 'Bayer AG', 'Industrial Automation', 'LOW', 512000.00, 'Sofia Roth', 'Daniel Keller', 'Marie Hoffmann', false, 100, 'PROJECTUM', 'Completed compliance renewal with a positive delivery margin.');

INSERT INTO project_planning (project_id, expected_start, expected_end, project_calendar, probability, keywords, subcontractors) VALUES
((SELECT id FROM projects WHERE code = 'NSC-26-021'), CURRENT_DATE - 45, CURRENT_DATE + 55, 'Germany Standard 8h', 75, 'vision inspection, camera, MES integration', 'Bosch Rexroth; Cognex integration partner'),
((SELECT id FROM projects WHERE code = 'NSC-25-008'), CURRENT_DATE - 420, CURRENT_DATE - 70, 'Germany Standard 8h', 100, 'hygienic filling, validation, compliance', 'TUV SUD');

INSERT INTO project_calendars (organisation_id, project_id, name, working_days, hours_per_day, start_time, is_default) VALUES
((SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM projects WHERE code = 'NSC-26-021'), 'Germany Standard 8h', '1,2,3,4,5', 8, '08:00', true),
((SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM projects WHERE code = 'NSC-25-008'), 'Germany Standard 8h', '1,2,3,4,5', 8, '08:00', true);

INSERT INTO project_tasks (project_id, organisation_id, parent_id, name, description, duration_days, planned_start, planned_end, baseline_start, baseline_end, actual_start, actual_end, percent_complete, allocation_percent, planned_hours, actual_hours, priority, schedule_mode, status, color, active, display_order, outline_level, task_type, wbs_code, department_code, department_id, customer_milestone, assigned_user_id, resource_type) VALUES
((SELECT id FROM projects WHERE code = 'NSC-26-001'), (SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM project_tasks WHERE project_id = (SELECT id FROM projects WHERE code = 'NSC-26-001') AND wbs_code = '1'), 'Steering Committee', 'Monthly governance and decision meeting.', 229, CURRENT_DATE - 68, CURRENT_DATE + 160, CURRENT_DATE - 68, CURRENT_DATE + 155, NULL, NULL, 56, 20, 96.00, 54.00, 108, 'MANUAL', 'IN_PROGRESS', '#1d4ed8', true, 16, 2, 'ACTIVITY', '1.3', 'PMO', (SELECT id FROM departments WHERE code='PMO' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), false, (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example'), 'PROJECT_CONTROLLER'),
((SELECT id FROM projects WHERE code = 'NSC-26-001'), (SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM project_tasks WHERE project_id = (SELECT id FROM projects WHERE code = 'NSC-26-001') AND wbs_code = '2'), 'Electrical Design Release', 'Issue drawings for customer review.', 8, CURRENT_DATE - 10, CURRENT_DATE - 2, CURRENT_DATE - 10, CURRENT_DATE - 5, CURRENT_DATE - 10, CURRENT_DATE - 1, 100, 100, 88.00, 96.00, 148, 'AUTO', 'COMPLETED', '#2563eb', true, 52, 2, 'MILESTONE', '2.1.1', 'ENG', (SELECT id FROM departments WHERE code='ENG' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), true, (SELECT id FROM users WHERE email='amir.benali@northstar-ia.example'), 'AUTOMATION_ENG'),
((SELECT id FROM projects WHERE code = 'NSC-26-001'), (SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM project_tasks WHERE project_id = (SELECT id FROM projects WHERE code = 'NSC-26-001') AND wbs_code = '2'), 'Panel Fabrication', 'Fabricate and inspect modified control panels.', 16, CURRENT_DATE, CURRENT_DATE + 15, CURRENT_DATE - 3, CURRENT_DATE + 12, CURRENT_DATE, NULL, 35, 100, 240.00, 84.00, 146, 'AUTO', 'IN_PROGRESS', '#2563eb', true, 54, 2, 'ACTIVITY', '2.1.2', 'ENG', (SELECT id FROM departments WHERE code='ENG' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), false, (SELECT id FROM users WHERE email='amir.benali@northstar-ia.example'), 'AUTOMATION_ENG'),
((SELECT id FROM projects WHERE code = 'NSC-26-001'), (SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM project_tasks WHERE project_id = (SELECT id FROM projects WHERE code = 'NSC-26-001') AND wbs_code = '2'), 'Safety PLC Delivery', 'Receive and inspect safety PLC components.', 1, CURRENT_DATE + 16, CURRENT_DATE + 16, CURRENT_DATE + 8, CURRENT_DATE + 8, NULL, NULL, 0, 100, 16.00, 0.00, 144, 'AUTO', 'NOT_STARTED', '#f59e0b', true, 56, 2, 'MILESTONE', '2.2.2', 'ENG', (SELECT id FROM departments WHERE code='ENG' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), false, NULL, 'PLC_DEVELOPER'),
((SELECT id FROM projects WHERE code = 'NSC-26-001'), (SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM project_tasks WHERE project_id = (SELECT id FROM projects WHERE code = 'NSC-26-001') AND wbs_code = '2'), 'Integrated Software Test', 'Run integrated PLC, HMI, and reporting test suite.', 12, CURRENT_DATE + 25, CURRENT_DATE + 36, CURRENT_DATE + 20, CURRENT_DATE + 31, NULL, NULL, 0, 100, 192.00, 0.00, 141, 'AUTO', 'NOT_STARTED', '#7c3aed', true, 68, 2, 'ACTIVITY', '2.2.3', 'ENG', (SELECT id FROM departments WHERE code='ENG' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), false, (SELECT id FROM users WHERE email='nina.vogel@northstar-ia.example'), 'PLC_DEVELOPER'),
((SELECT id FROM projects WHERE code = 'NSC-26-001'), (SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM project_tasks WHERE project_id = (SELECT id FROM projects WHERE code = 'NSC-26-001') AND wbs_code = '3'), 'Operator Training', 'Deliver operator and maintenance training.', 5, CURRENT_DATE + 105, CURRENT_DATE + 109, CURRENT_DATE + 100, CURRENT_DATE + 104, NULL, NULL, 0, 100, 80.00, 0.00, 125, 'AUTO', 'NOT_STARTED', '#059669', true, 82, 2, 'ACTIVITY', '3.1.1', 'OPS', (SELECT id FROM departments WHERE code='OPS' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), true, (SELECT id FROM users WHERE email='marta.klein@northstar-ia.example'), 'SITE_TECHNICIAN'),
((SELECT id FROM projects WHERE code = 'NSC-26-001'), (SELECT id FROM organisations WHERE code = 'NSIA'), (SELECT id FROM project_tasks WHERE project_id = (SELECT id FROM projects WHERE code = 'NSC-26-001') AND wbs_code = '3'), 'Project Close-out', 'Complete as-built records, handover, and financial close.', 10, CURRENT_DATE + 145, CURRENT_DATE + 154, CURRENT_DATE + 140, CURRENT_DATE + 149, NULL, NULL, 0, 50, 80.00, 0.00, 118, 'MANUAL', 'NOT_STARTED', '#059669', true, 95, 2, 'ACTIVITY', '3.2', 'PMO', (SELECT id FROM departments WHERE code='PMO' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), false, (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example'), 'PROJECT_CONTROLLER');

INSERT INTO task_dependencies (project_id, predecessor_task_id, successor_task_id, dependency_type, lag_days) VALUES
((SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.1.2'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.2'), 'FS', 0),
((SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.2'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.3'), 'FS', 0),
((SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.1'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.1.1'), 'FS', 0);

INSERT INTO finance_entries (owner_name, owner_id, organisation_id, project_id, project_task_id, wbs_code, description, level, sales, budget, commitment, actual_cost, forecast, owner_key, row_type, hour_rate, is_summary) VALUES
('Nina Vogel', (SELECT id FROM users WHERE email='nina.vogel@northstar-ia.example'), (SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2'), '2.2', 'PLC development labour', 2, 310000.00, 274000.00, 190000.00, 154000.00, 298000.00, 'SOFTWARE', 'HOUR', 92.00, false),
('Elena Fischer', (SELECT id FROM users WHERE email='elena.fischer@northstar-ia.example'), (SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.1.2'), '2.1.2', 'Panel fabrication vendor cost', 2, 180000.00, 142000.00, 138000.00, 115000.00, 168000.00, 'ENGINEERING', 'COST', NULL, false),
('Lukas Brandt', (SELECT id FROM users WHERE email='lukas.brandt@northstar-ia.example'), (SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.2'), '2.2.2', 'Safety PLC vendor materials', 2, 235000.00, 198000.00, 188000.00, 0.00, 226000.00, 'OPERATIONS', 'COST', NULL, false),
('Lukas Brandt', (SELECT id FROM users WHERE email='lukas.brandt@northstar-ia.example'), (SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.1.1'), '3.1.1', 'Operator training delivery', 2, 65000.00, 52000.00, 0.00, 0.00, 48000.00, 'OPERATIONS', 'HOUR', 78.00, false),
('Jonas Meier', (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example'), (SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.2'), '3.2', 'Project close-out labour', 2, 40000.00, 32000.00, 0.00, 0.00, 29000.00, 'PMO', 'HOUR', 84.00, false),
('Sofia Roth', (SELECT id FROM users WHERE email='sofia.roth@northstar-ia.example'), (SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-25-008'), NULL, '1', 'Completed compliance renewal', 1, 530000.00, 530000.00, 515000.00, 512000.00, 512000.00, 'PMO', 'SUMMARY', NULL, true);

INSERT INTO forecast_entries (organisation_id, project_id, finance_entry_id, wbs_code, period_key, amount) VALUES
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM finance_entries WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2'), '2.2', to_char(CURRENT_DATE, 'YYYY-MM'), 42000.00),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM finance_entries WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2'), '2.2', to_char(CURRENT_DATE + INTERVAL '1 month', 'YYYY-MM'), 44000.00),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM finance_entries WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.1.2'), '2.1.2', to_char(CURRENT_DATE + INTERVAL '1 month', 'YYYY-MM'), 68000.00),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM finance_entries WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.2'), '2.2.2', to_char(CURRENT_DATE + INTERVAL '2 months', 'YYYY-MM'), 118000.00),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM finance_entries WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.1.1'), '3.1.1', to_char(CURRENT_DATE + INTERVAL '4 months', 'YYYY-MM'), 48000.00),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM finance_entries WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.2'), '3.2', to_char(CURRENT_DATE + INTERVAL '5 months', 'YYYY-MM'), 29000.00);

INSERT INTO risk_items (organisation_id, project_id, risk_type, state, description, input_date, due_date, mitigation, resource_type_id, owner_user_id, wbs_code, impact, probability, variance_status, approved_by, approved_at, notes) VALUES
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'risk', 'new', 'Customer production blackout window may restrict final commissioning dates.', CURRENT_DATE - 3, CURRENT_DATE + 20, 'Confirm outage calendar at the next steering committee.', (SELECT id FROM resource_types WHERE code='PROJECT_CONTROLLER' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example'), '3.1', '2', 30, NULL, NULL, NULL, 'Awaiting customer confirmation.'),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'risk', 'closed', 'Electrical drawing review threatened design release.', CURRENT_DATE - 40, CURRENT_DATE - 5, 'Completed joint review and released corrected drawings.', (SELECT id FROM resource_types WHERE code='AUTOMATION_ENG' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), (SELECT id FROM users WHERE email='amir.benali@northstar-ia.example'), '2.1.1', '2', 20, NULL, NULL, NULL, 'Closed after release.'),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'risk', 'variance', 'Safety PLC supplier premium is above the approved material budget.', CURRENT_DATE - 1, CURRENT_DATE + 7, 'Use alternate allocation and request customer approval for premium.', (SELECT id FROM resource_types WHERE code='PLC_DEVELOPER' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), (SELECT id FROM users WHERE email='elena.fischer@northstar-ia.example'), '2.2.2', '5', 80, 'open', NULL, NULL, 'Critical cost variance awaiting approval.'),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'opportunity', 'managing', 'Reuse validated HMI library to shorten integrated software testing.', CURRENT_DATE, CURRENT_DATE + 15, 'Confirm library compatibility during test preparation.', (SELECT id FROM resource_types WHERE code='PLC_DEVELOPER' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), (SELECT id FROM users WHERE email='nina.vogel@northstar-ia.example'), '2.2.3', '2', 65, NULL, NULL, NULL, 'Expected to save approximately three engineering days.');

INSERT INTO change_requests (organisation_id, project_id, title, status, request_date, value_amount, cost_amount, owner, requester_id, approver_id, affected_task_id, note) VALUES
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'CR-03 Safety PLC Supplier Premium', 'open', CURRENT_DATE, 18000.00, 22000.00, 'Lukas Brandt', (SELECT id FROM users WHERE email='lukas.brandt@northstar-ia.example'), NULL, (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.2'), 'Premium required to protect the planned factory acceptance date.'),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'CR-04 Additional Operator Training Session', 'refused', CURRENT_DATE - 5, 12000.00, 8500.00, 'Marta Klein', (SELECT id FROM users WHERE email='marta.klein@northstar-ia.example'), (SELECT id FROM users WHERE email='daniel.keller@northstar-ia.example'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.1.1'), 'Customer requested an extra shift; existing training approach was retained.'),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'CR-05 Dashboard Enhancement Scope', 'cancelled', CURRENT_DATE - 12, 30000.00, 26000.00, 'Jonas Meier', (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example'), NULL, (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.3'), 'Cancelled after customer elected to use standard reporting.');

INSERT INTO change_request_history (change_request_id, action, performed_by, performed_by_user_id, created_at) VALUES
((SELECT id FROM change_requests WHERE title='CR-03 Safety PLC Supplier Premium'), 'Created', 'Lukas Brandt', (SELECT id FROM users WHERE email='lukas.brandt@northstar-ia.example'), CURRENT_TIMESTAMP - INTERVAL '1 day'),
((SELECT id FROM change_requests WHERE title='CR-04 Additional Operator Training Session'), 'Refused after commercial review', 'Daniel Keller', (SELECT id FROM users WHERE email='daniel.keller@northstar-ia.example'), CURRENT_TIMESTAMP - INTERVAL '2 days'),
((SELECT id FROM change_requests WHERE title='CR-05 Dashboard Enhancement Scope'), 'Cancelled by requester', 'Jonas Meier', (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example'), CURRENT_TIMESTAMP - INTERVAL '5 days');

INSERT INTO action_items (organisation_id, project_id, title, description, action_type, department_code, department_id, priority, status, customer_visible, inserted_date, due_date, owner_id, risk_id, change_request_id, project_task_id) VALUES
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'Validate production blackout calendar', 'Obtain confirmed customer production blackout dates for commissioning.', 'action', 'PMO', (SELECT id FROM departments WHERE code='PMO' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), 'medium', 'todo', true, CURRENT_DATE - 2, CURRENT_DATE + 5, (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example'), (SELECT id FROM risk_items WHERE description='Customer production blackout window may restrict final commissioning dates.'), NULL, (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.1')),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'Escalate safety PLC premium', 'Secure executive decision on supplier premium and customer recovery approach.', 'issue', 'OPS', (SELECT id FROM departments WHERE code='OPS' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), 'high', 'blocked', false, CURRENT_DATE - 4, CURRENT_DATE - 1, (SELECT id FROM users WHERE email='lukas.brandt@northstar-ia.example'), (SELECT id FROM risk_items WHERE description='Safety PLC supplier premium is above the approved material budget.'), (SELECT id FROM change_requests WHERE title='CR-03 Safety PLC Supplier Premium'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.2')),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'Reuse validated HMI library', 'Complete technical check of the approved HMI library.', 'action', 'ENG', (SELECT id FROM departments WHERE code='ENG' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), 'low', 'done', false, CURRENT_DATE - 7, CURRENT_DATE - 1, (SELECT id FROM users WHERE email='nina.vogel@northstar-ia.example'), (SELECT id FROM risk_items WHERE description='Reuse validated HMI library to shorten integrated software testing.'), NULL, (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.3')),
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), 'Book operator training rooms', 'Reserve training rooms and prepare attendance list.', 'action', 'OPS', (SELECT id FROM departments WHERE code='OPS' AND organisation_id=(SELECT id FROM organisations WHERE code='NSIA')), 'medium', 'review', true, CURRENT_DATE - 1, CURRENT_DATE + 40, (SELECT id FROM users WHERE email='marta.klein@northstar-ia.example'), NULL, NULL, (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='3.1.1'));

INSERT INTO action_assignees (action_item_id, assignee_name, assignee_user_id) VALUES
((SELECT id FROM action_items WHERE title='Validate production blackout calendar'), 'Jonas Meier', (SELECT id FROM users WHERE email='jonas.meier@northstar-ia.example')),
((SELECT id FROM action_items WHERE title='Escalate safety PLC premium'), 'Lukas Brandt', (SELECT id FROM users WHERE email='lukas.brandt@northstar-ia.example')),
((SELECT id FROM action_items WHERE title='Book operator training rooms'), 'Marta Klein', (SELECT id FROM users WHERE email='marta.klein@northstar-ia.example'));

INSERT INTO action_comments (action_item_id, author, author_user_id, text, created_at) VALUES
((SELECT id FROM action_items WHERE title='Escalate safety PLC premium'), 'Lukas Brandt', (SELECT id FROM users WHERE email='lukas.brandt@northstar-ia.example'), 'Supplier can hold the allocation only until Friday; approval is required this week.', CURRENT_TIMESTAMP - INTERVAL '1 day'),
((SELECT id FROM action_items WHERE title='Reuse validated HMI library'), 'Nina Vogel', (SELECT id FROM users WHERE email='nina.vogel@northstar-ia.example'), 'Compatibility check completed successfully; three engineering days saved.', CURRENT_TIMESTAMP - INTERVAL '1 day');

INSERT INTO notifications (organisation_id, project_id, task_id, recipient_user_id, recipient_email, channel, status, severity, subject, message, retry_count, error_message, created_at, sent_at, next_retry_at) VALUES
((SELECT id FROM organisations WHERE code='NSIA'), (SELECT id FROM projects WHERE code='NSC-26-001'), (SELECT id FROM project_tasks WHERE project_id=(SELECT id FROM projects WHERE code='NSC-26-001') AND wbs_code='2.2.2'), (SELECT id FROM users WHERE email='elena.fischer@northstar-ia.example'), 'elena.fischer@northstar-ia.example', 'EMAIL', 'FAILED', 'ERROR', 'Safety PLC approval required', 'The safety PLC premium requires an approval decision.', 2, 'Local demo SMTP is not configured.', CURRENT_TIMESTAMP - INTERVAL '2 hours', NULL, CURRENT_TIMESTAMP + INTERVAL '1 day');

COMMIT;
