package com.ercopac.ercopac_tracker.ticketing.domain;
public enum TicketActivityType { CREATED, UPDATED, STATUS_CHANGED, PRIORITY_CHANGED, ASSIGNED, ESCALATED, RESOLVED, REOPENED, CLOSED, MESSAGE_ADDED, ATTACHMENT_UPLOADED, ATTACHMENT_REMOVED }
