spring.application.name=ercopac-tracker

server.port=${PORT:8087}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ercopac_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ercopac_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ercopac_pass}

spring.jpa.properties.hibernate.default_schema=public
spring.datasource.hikari.schema=public

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:myLocalJwtSecret12345678901234567890}