spring.application.name=ercopac-tracker

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ercopac_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ercopac_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ercopac_pass}

spring.jpa.properties.hibernate.default_schema=public
spring.datasource.hikari.schema=public

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8087}
jwt.secret=${JWT_SECRET:myLocalJwtSecret12345678901234567890}