package com.ercopac.ercopac_tracker.ticketing.repository;
import com.ercopac.ercopac_tracker.ticketing.domain.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.repository.*; import org.springframework.data.repository.query.Param; import java.time.Instant; import java.util.*;
public interface TicketRepository extends JpaRepository<Ticket,Long> {
 @Query("select t from Ticket t where (:platform = true or t.organisation.id = :organisationId) and (:clientOnly = false or t.clientUser.id = :userId or t.createdByUser.id = :userId) and (:search is null or lower(t.ticketNumber) like :search or lower(t.subject) like :search) and (:status is null or t.status = :status) and (:priority is null or t.priority = :priority) and (:category is null or t.category = :category) and (:assigneeId is null or t.assignedSalesManager.id = :assigneeId) and (:creatorId is null or t.createdByUser.id = :creatorId) and t.createdAt >= :fromDate and t.createdAt <= :toDate")
 Page<Ticket> search(@Param("platform") boolean platform,@Param("organisationId") Long organisationId,@Param("clientOnly") boolean clientOnly,@Param("userId") Long userId,@Param("search") String search,@Param("status") TicketStatus status,@Param("priority") TicketPriority priority,@Param("category") TicketCategory category,@Param("assigneeId") Long assigneeId,@Param("creatorId") Long creatorId,@Param("fromDate") Instant fromDate,@Param("toDate") Instant toDate,Pageable pageable);
 Optional<Ticket> findFirstByTicketNumberStartingWithOrderByTicketNumberDesc(String prefix);
 Optional<Ticket> findByTicketNumber(String ticketNumber);
 @Query("select count(t) from Ticket t where (:platform = true or t.organisation.id = :organisationId) and (:clientOnly = false or t.clientUser.id = :userId or t.createdByUser.id = :userId) and t.status = :status") long countVisibleByStatus(boolean platform,Long organisationId,boolean clientOnly,Long userId,TicketStatus status);
 @Query("select count(t) from Ticket t where (:platform = true or t.organisation.id = :organisationId) and (:clientOnly = false or t.clientUser.id = :userId or t.createdByUser.id = :userId) and t.createdAt >= :today") long countVisibleCreatedSince(boolean platform,Long organisationId,boolean clientOnly,Long userId,Instant today);
}
