package com.ercopac.ercopac_tracker.ticketing.service;

import com.ercopac.ercopac_tracker.organisation.domain.Organisation;
import com.ercopac.ercopac_tracker.organisation.repository.OrganisationRepository;
import com.ercopac.ercopac_tracker.security.SecurityUtils;
import com.ercopac.ercopac_tracker.ticketing.domain.*;
import com.ercopac.ercopac_tracker.ticketing.dto.TicketDtos.*;
import com.ercopac.ercopac_tracker.ticketing.repository.*;
import com.ercopac.ercopac_tracker.user.*;
import jakarta.transaction.Transactional;
import org.springframework.data.domain.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*; import java.util.concurrent.atomic.AtomicInteger; import java.util.stream.Collectors;

@Service @Transactional
public class TicketService {
 private final TicketRepository tickets; private final TicketMessageRepository messages; private final TicketActivityRepository activities; private final TicketAttachmentRepository attachments; private final TicketReadStateRepository readStates; private final UserRepository users; private final OrganisationRepository organisations; private final SecurityUtils security; private final TicketStatusTransitionValidator transitions;
 public TicketService(TicketRepository tickets,TicketMessageRepository messages,TicketActivityRepository activities,TicketAttachmentRepository attachments,TicketReadStateRepository readStates,UserRepository users,OrganisationRepository organisations,SecurityUtils security,TicketStatusTransitionValidator transitions){this.tickets=tickets;this.messages=messages;this.activities=activities;this.attachments=attachments;this.readStates=readStates;this.users=users;this.organisations=organisations;this.security=security;this.transitions=transitions;}
 public Page<TicketSummary> list(String search,TicketStatus status,TicketPriority priority,TicketCategory category,Long organisationId,Long assigneeId,Long creatorId,Instant from,Instant to,Pageable pageable){ AppUser actor=current(); Scope s=scope(actor); ensureTicketRole(s); if(organisationId!=null&&!s.platform&& !organisationId.equals(s.organisationId)) throw forbidden(); return tickets.search(s.platform,organisationId!=null?organisationId:s.organisationId,s.client,actor.getId(),pattern(search),status,priority,category,assigneeId,creatorId,from==null?Instant.EPOCH:from,to==null?Instant.parse("9999-12-31T23:59:59Z"):to,pageable).map(t->summary(t,actor)); }
 public TicketDetails get(Long id){ AppUser actor=current(); Ticket t=accessible(id,actor); markRead(t,actor); return details(t,actor); }
 public TicketDetails create(CreateTicketRequest request){ AppUser actor=current(); Scope s=scope(actor); ensureTicketRole(s); Organisation org=resolveOrganisation(request.organisationId(),s); if(s.client && request.organisationId()!=null&&!request.organisationId().equals(s.organisationId))throw forbidden(); AppUser client=s.client?actor:resolveClient(request.clientUserId(),org); Ticket t=new Ticket();t.setTicketNumber(nextNumber());t.setSubject(trim(request.subject()));t.setDescription(trim(request.description()));t.setOrganisation(org);t.setCreatedByUser(actor);t.setClientUser(client);t.setCategory(request.category());t.setPriority(request.priority());t.setOrigin(request.origin()==null?TicketOrigin.WEB:request.origin());t.setSite(blankToNull(request.site()));t=tickets.save(t); activity(t,actor,TicketActivityType.CREATED,null,null,"Ticket created"); if(request.initialMessage()!=null&&!request.initialMessage().isBlank()) addMessage(t.getId(),new MessageRequest(request.initialMessage(),false)); return details(t,actor); }
 public TicketDetails update(Long id,UpdateTicketRequest r){AppUser a=current(); Ticket t=manageable(id,a); version(t,r.version()); if(r.subject()!=null)t.setSubject(trim(r.subject())); if(r.description()!=null)t.setDescription(trim(r.description()));if(r.category()!=null)t.setCategory(r.category());if(r.origin()!=null)t.setOrigin(r.origin());if(r.site()!=null)t.setSite(blankToNull(r.site())); activity(t,a,TicketActivityType.UPDATED,null,null,"Ticket information updated");return details(t,a);}
 public TicketDetails changeStatus(Long id,StatusRequest r){AppUser a=current();Ticket t=manageable(id,a);version(t,r.version()); transitions.validate(t.getStatus(),r.status(),platform(a)); TicketStatus old=t.getStatus();t.setStatus(r.status());Instant now=Instant.now(); if(r.status()==TicketStatus.RESOLVED)t.setResolvedAt(now);if(r.status()==TicketStatus.CLOSED)t.setClosedAt(now);activity(t,a,typeFor(r.status()),old.name(),r.status().name(),"Status changed to "+r.status());return details(t,a);}
 public TicketDetails changePriority(Long id,PriorityRequest r){AppUser a=current();Ticket t=manageable(id,a);version(t,r.version());TicketPriority old=t.getPriority();t.setPriority(r.priority());activity(t,a,TicketActivityType.PRIORITY_CHANGED,old.name(),r.priority().name(),"Priority changed to "+r.priority());return details(t,a);}
 public TicketDetails assign(Long id,AssignmentRequest r){AppUser a=current();Ticket t=manageable(id,a);version(t,r.version());AppUser assignee=r.assigneeId()==null?null:users.findByIdAndOrganisation_Id(r.assigneeId(),t.getOrganisation().getId()).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Assignee is outside the ticket organisation.")); if(assignee!=null&&!isManager(assignee))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Assignee must be an authorised Sales Manager.");String old=t.getAssignedSalesManager()==null?null:t.getAssignedSalesManager().getFullName();t.setAssignedSalesManager(assignee);activity(t,a,TicketActivityType.ASSIGNED,old,assignee==null?null:assignee.getFullName(),assignee==null?"Ticket unassigned":"Ticket assigned");return details(t,a);}
 public TicketDetails escalate(Long id,Long version){AppUser a=current();Ticket t=manageable(id,a);version(t,version); transitions.validate(t.getStatus(),TicketStatus.ESCALATED,platform(a));TicketStatus old=t.getStatus();t.setStatus(TicketStatus.ESCALATED);t.setEscalationLevel(t.getEscalationLevel()+1);activity(t,a,TicketActivityType.ESCALATED,old.name(),"ESCALATED","Ticket escalated to level "+t.getEscalationLevel());return details(t,a);}
 public TicketDetails resolve(Long id,Long version){return changeStatus(id,new StatusRequest(TicketStatus.RESOLVED,version));} public TicketDetails reopen(Long id,Long version){AppUser a=current();Ticket t=accessible(id,a);if(scope(a).client&&t.getStatus()!=TicketStatus.RESOLVED)throw forbidden();if(!scope(a).client) return changeStatus(id,new StatusRequest(TicketStatus.REOPENED,version));version(t,version);transitions.validate(t.getStatus(),TicketStatus.REOPENED,false);t.setStatus(TicketStatus.REOPENED);activity(t,a,TicketActivityType.REOPENED,"RESOLVED","REOPENED","Ticket reopened by client");return details(t,a);} public TicketDetails close(Long id,Long version){AppUser a=current();Ticket t=accessible(id,a);if(scope(a).client&&t.getStatus()!=TicketStatus.RESOLVED)throw new TicketConflictException("Only resolved tickets can be closed by a client.");if(!scope(a).client)return changeStatus(id,new StatusRequest(TicketStatus.CLOSED,version));version(t,version);t.setStatus(TicketStatus.CLOSED);t.setClosedAt(Instant.now());activity(t,a,TicketActivityType.CLOSED,"RESOLVED","CLOSED","Ticket closed by client");return details(t,a);}
 public TicketMessageDto addMessage(Long id,MessageRequest r){AppUser a=current();Ticket t=accessible(id,a);if(scope(a).client&&r.internalNote())throw forbidden();if(r.message()==null||r.message().trim().isEmpty())throw new IllegalArgumentException("Message cannot be empty.");TicketMessage m=new TicketMessage();m.setTicket(t);m.setSender(a);m.setMessage(trim(r.message()));m.setInternalNote(r.internalNote());m=messages.save(m);t.setLastMessageAt(m.getCreatedAt());activity(t,a,TicketActivityType.MESSAGE_ADDED,null,null,r.internalNote()?"Internal note added":"Message added");return message(m);}
 public TicketMessageDto addMessageForUser(Long id,Long userId,MessageRequest r){AppUser a=users.findById(userId).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Current account no longer exists."));Ticket t=accessible(id,a);if(scope(a).client&&r.internalNote())throw forbidden();if(r.message()==null||r.message().trim().isEmpty())throw new IllegalArgumentException("Message cannot be empty.");TicketMessage m=new TicketMessage();m.setTicket(t);m.setSender(a);m.setMessage(trim(r.message()));m.setInternalNote(r.internalNote());m=messages.save(m);t.setLastMessageAt(m.getCreatedAt());activity(t,a,TicketActivityType.MESSAGE_ADDED,null,null,r.internalNote()?"Internal note added":"Message added");return message(m);}
 public List<TicketMessageDto> messages(Long id){AppUser a=current();Ticket t=accessible(id,a);return (scope(a).client?messages.findByTicket_IdAndInternalNoteFalseOrderByCreatedAtAsc(id):messages.findByTicket_IdOrderByCreatedAtAsc(id)).stream().filter(m->!m.isDeleted()).map(this::message).toList();}
 public List<TicketActivityDto> activity(Long id){AppUser a=current();accessible(id,a);return activities.findByTicket_IdOrderByCreatedAtAsc(id).stream().map(this::activityDto).toList();}
 public TicketStatistics stats(){AppUser a=current();Scope s=scope(a);ensureTicketRole(s);Instant today=LocalDate.now(ZoneOffset.UTC).atStartOfDay(ZoneOffset.UTC).toInstant();Map<TicketStatus,Long> counts=new EnumMap<>(TicketStatus.class);for(TicketStatus status:List.of(TicketStatus.OPEN,TicketStatus.IN_PROGRESS,TicketStatus.ESCALATED,TicketStatus.RESOLVED,TicketStatus.CLOSED))counts.put(status,tickets.countVisibleByStatus(s.platform,s.organisationId,s.client,a.getId(),status));return new TicketStatistics(counts.get(TicketStatus.OPEN),counts.get(TicketStatus.IN_PROGRESS),counts.get(TicketStatus.ESCALATED),counts.get(TicketStatus.RESOLVED),counts.get(TicketStatus.CLOSED),tickets.countVisibleCreatedSince(s.platform,s.organisationId,s.client,a.getId(),today),0,0,List.of(),List.of());}
 public boolean canAccess(Long ticketId,Long userId){try{AppUser a=users.findById(userId).orElse(null);if(a==null)return false;accessible(ticketId,a);return true;}catch(RuntimeException ex){return false;}}
 public Ticket requireAccessible(Long id){return accessible(id,current());} public AppUser currentUser(){return current();} public boolean mayManageCurrent(){return scope(current()).manager;}
 private Ticket accessible(Long id,AppUser a){Ticket t=tickets.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Ticket not found."));Scope s=scope(a);ensureTicketRole(s);if(!s.platform&&!Objects.equals(t.getOrganisation().getId(),s.organisationId))throw forbidden();if(s.client&&!Objects.equals(t.getClientUser()==null?null:t.getClientUser().getId(),a.getId())&&!Objects.equals(t.getCreatedByUser().getId(),a.getId()))throw forbidden();return t;} private Ticket manageable(Long id,AppUser a){if(!scope(a).manager)throw forbidden();return accessible(id,a);} private AppUser current(){Long id=security.getCurrentUserId();return users.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Current account no longer exists."));} private Scope scope(AppUser a){return new Scope(platform(a),a.getRole()==Role.CLIENT,isManager(a),a.getOrganisation()==null?null:a.getOrganisation().getId());} private void ensureTicketRole(Scope s){if(!s.client&&!s.manager)throw forbidden();} private boolean platform(AppUser a){return a.getRole()==Role.PLATFORM_OWNER||a.getRole()==Role.PLATFORM_ADMIN;} private boolean isManager(AppUser a){return a.getRole()==Role.SALES_MANAGER||platform(a)||a.getRole()==Role.ORG_ADMIN;} private Organisation resolveOrganisation(Long requested,Scope s){Long id=requested==null?s.organisationId:requested;if(id==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"An organisation is required.");if(!s.platform&&!id.equals(s.organisationId))throw forbidden();return organisations.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Organisation not found."));} private AppUser resolveClient(Long id,Organisation org){if(id==null)return null;AppUser u=users.findByIdAndOrganisation_Id(id,org.getId()).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Client is outside the selected organisation."));if(u.getRole()!=Role.CLIENT)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Selected client must have CLIENT role.");return u;}
 private String nextNumber(){String prefix="TKT-"+Year.now(ZoneOffset.UTC)+"-";Ticket latest=tickets.findFirstByTicketNumberStartingWithOrderByTicketNumberDesc(prefix).orElse(null);int seq=latest==null?1:Integer.parseInt(latest.getTicketNumber().substring(prefix.length()))+1;return prefix+String.format("%06d",seq);} private void version(Ticket t,Long expected){if(expected==null||!Objects.equals(t.getVersion(),expected))throw new TicketConflictException("Ticket was updated by another user. Refresh and try again.");} private String pattern(String v){return v==null||v.isBlank()?null:"%"+v.trim().toLowerCase()+"%";} private String trim(String v){if(v==null||v.trim().isEmpty())throw new IllegalArgumentException("Value cannot be blank.");return v.trim();}private String blankToNull(String v){return v==null||v.trim().isEmpty()?null:v.trim();}private ResponseStatusException forbidden(){return new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not have access to this ticket.");}
 private void activity(Ticket t,AppUser actor,TicketActivityType type,String old,String value,String description){TicketActivity h=new TicketActivity();h.setTicket(t);h.setActor(actor);h.setActivityType(type);h.setPreviousValue(old);h.setNewValue(value);h.setDescription(description);activities.save(h);} private TicketActivityType typeFor(TicketStatus s){return switch(s){case ESCALATED->TicketActivityType.ESCALATED;case RESOLVED->TicketActivityType.RESOLVED;case REOPENED->TicketActivityType.REOPENED;case CLOSED->TicketActivityType.CLOSED;default->TicketActivityType.STATUS_CHANGED;};}
 private TicketSummary summary(Ticket t,AppUser a){Instant read=readStates.findByTicket_IdAndUser_Id(t.getId(),a.getId()).map(TicketReadState::getLastReadAt).orElse(Instant.EPOCH);return new TicketSummary(t.getId(),t.getTicketNumber(),t.getSubject(),t.getOrganisation().getId(),t.getOrganisation().getName(),t.getStatus(),t.getPriority(),t.getCategory(),t.getSite(),user(t.getClientUser()),user(t.getAssignedSalesManager()),t.getCreatedAt(),t.getUpdatedAt(),t.getLastMessageAt(),messages.countByTicket_IdAndCreatedAtAfterAndSender_IdNot(t.getId(),read,a.getId()));} private TicketDetails details(Ticket t,AppUser a){return new TicketDetails(summary(t,a),t.getDescription(),t.getOrigin(),t.getEscalationLevel(),t.getResolvedAt(),t.getClosedAt(),t.getVersion(),messages(t.getId()),activity(t.getId()),attachments.findByTicket_IdOrderByUploadedAtAsc(t.getId()).stream().map(this::attachment).toList(),scope(a).manager,t.getStatus()==TicketStatus.RESOLVED||scope(a).manager);} private UserSummary user(AppUser u){return u==null?null:new UserSummary(u.getId(),u.getFullName(),u.getEmail(),u.getRole().name());} private TicketMessageDto message(TicketMessage m){return new TicketMessageDto(m.getId(),m.getMessage(),m.getMessageType(),m.isInternalNote(),user(m.getSender()),m.getCreatedAt(),m.getEditedAt());}private TicketActivityDto activityDto(TicketActivity h){return new TicketActivityDto(h.getId(),h.getActivityType(),h.getPreviousValue(),h.getNewValue(),h.getDescription(),user(h.getActor()),h.getCreatedAt());}private TicketAttachmentDto attachment(TicketAttachment x){return new TicketAttachmentDto(x.getId(),x.getOriginalFileName(),x.getContentType(),x.getFileSize(),user(x.getUploadedBy()),x.getUploadedAt());}private void markRead(Ticket t,AppUser a){TicketReadState s=readStates.findByTicket_IdAndUser_Id(t.getId(),a.getId()).orElseGet(TicketReadState::new);s.setTicket(t);s.setUser(a);s.setLastReadAt(Instant.now());readStates.save(s);} private record Scope(boolean platform,boolean client,boolean manager,Long organisationId){}
}
