package com.ercopac.ercopac_tracker.ticketing.dto;
import com.ercopac.ercopac_tracker.ticketing.domain.*; import jakarta.validation.constraints.*; import java.time.Instant; import java.util.List;
public final class TicketDtos { private TicketDtos(){}
 public record CreateTicketRequest(@NotBlank @Size(max=250) String subject,@NotBlank @Size(max=8000) String description,@NotNull TicketCategory category,@NotNull TicketPriority priority,TicketOrigin origin,@Size(max=160) String site,Long organisationId,Long clientUserId,@Size(max=8000) String initialMessage){}
 public record UpdateTicketRequest(@Size(max=250) String subject,@Size(max=8000) String description,TicketCategory category,TicketOrigin origin,@Size(max=160) String site,Long version){}
 public record StatusRequest(@NotNull TicketStatus status,@NotNull Long version){} public record PriorityRequest(@NotNull TicketPriority priority,@NotNull Long version){} public record AssignmentRequest(Long assigneeId,@NotNull Long version){} public record MessageRequest(@NotBlank @Size(max=8000) String message,boolean internalNote){}
 public record UserSummary(Long id,String fullName,String email,String role){} public record TicketSummary(Long id,String ticketNumber,String subject,Long organisationId,String organisationName,TicketStatus status,TicketPriority priority,TicketCategory category,String site,UserSummary client,UserSummary assignee,Instant createdAt,Instant updatedAt,Instant lastMessageAt,long unreadCount){}
 public record TicketDetails(TicketSummary ticket,String description,TicketOrigin origin,int escalationLevel,Instant resolvedAt,Instant closedAt,Long version,List<TicketMessageDto> messages,List<TicketActivityDto> activities,List<TicketAttachmentDto> attachments,boolean canManage,boolean canClose){}
 public record TicketMessageDto(Long id,String message,String messageType,boolean internalNote,UserSummary sender,Instant createdAt,Instant editedAt){} public record TicketActivityDto(Long id,TicketActivityType activityType,String previousValue,String newValue,String description,UserSummary actor,Instant createdAt){} public record TicketAttachmentDto(Long id,String originalFileName,String contentType,long fileSize,UserSummary uploadedBy,Instant uploadedAt){}
 public record TicketStatistics(long open,long inProgress,long escalated,long resolved,long closed,long createdToday,long overdue,double averageResolutionHours,List<Breakdown> byPriority,List<Breakdown> byCategory){} public record Breakdown(String key,long count){}
}
